sudo: required
services:
  - docker

before_install:
  - docker build -t benbenek/ci-test -f Dockerfile.dev .

script:
  - docker run benbenek/ci-test npm run test:unit

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "ci-test"
  env: "CiTest-env"
  bucket_name: "elasticbeanstalk-eu-central-1-832952669290"
  bucket_path: "ci-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

